# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7004afc26bfba10ce7037776b7bc43158c1fa3a5ae95dfac81e25a0e7687fdea88697bcfba283f33caf2741e8b950e7f55a9be0619a4bb4bd721a36451fd8318

test:
  secret_key_base: 71073466ca1f397650e3c102941b338c81d105446fc9f4073b10f41a4efb742fef141ffde5381c3af4a18fd2a3c80a11c5aec68d5ab76ae7d0a282800a7726e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
